name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_map: ^8.3.1
  geolocator: ^14.0.2
  latlong2: ^0.10.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter_launcher_name:
  name: "SCA"
flutter:
  assets:
    - assets/images/bg_SCA.jpg
    - assets/images/Icon.jpg
    - assets/images/OIcon.png
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/Icon.jpg" 
  
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/Icon.jpg"
  web:
    generate: true
    image_path: "assets/images/Icon.jpg"
  windows:
    generate: true
    image_path: "assets/images/Icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/Icon.jpg"
  linux:
    generate: true
    image_path: "assets/images/Icon.jpg"
